runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app
threadsafe: true

runtime_config:
  python_version: 3

env_variables:
    SQLALCHEMY_DATABASE_URI: >-
      mysql+pymysql://<user>:<password>@/<db>?unix_socket=/cloudsql/<instance_connection_id>

beta_settings:
    cloud_sql_instances: <instance_connection_id>
